services:
  aws-cost-monitor:
    build: 
      context: .
      dockerfile: Dockerfile
    image: aws-cost-monitor:latest
    container_name: aws-cost-monitor
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - DB_TYPE=${DB_TYPE:-sqlite}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_NAME=${DB_NAME:-aws_cost_monitor}
      - DB_PATH=${DB_PATH:-/app/data/cost_history.db}
      - LOG_PATH=${LOG_PATH:-}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped
    labels:
      - "com.aws-cost-monitor.description=AWS成本监控系统"
      - "com.aws-cost-monitor.version=2.0.0"
      - "com.aws-cost-monitor.database=${DB_TYPE:-sqlite}"