services:
  aws-cost-monitor:
    build: 
      context: .
      dockerfile: Dockerfile
    image: aws-cost-monitor:latest
    container_name: aws-cost-monitor
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    restart: unless-stopped
    labels:
      - "com.aws-cost-monitor.description=AWS成本监控系统"
      - "com.aws-cost-monitor.version=1.0.2"