version: '3.8'

services:
  aws-cost-monitor:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    restart: unless-stopped